### ISSUE TITLE
运行env.test.py时，在env.reset()处报错：TypeError: cannot unpack non-iterable ImageState object

### ISSUE THREAD

**Issue by zks204** [DRL-Navigation/img_env#2]
你好，我运行到env.test.py的env.reset()时报：TypeError: cannot unpack non-iterable ImageState object错误，我感觉因该是环境数据与返回数据不匹配造成的，但我找了很久都不知道应该修改哪里。能帮我解决下吗？？非常感谢。

**Comment by SpikeJishuo** [comment]
我也遇到了这个错误，可能是因为gym版本太高引起的不兼容报错，我的gym是0.26.0，改为0.22.0版本能够运行了，希望能帮上忙。

**Comment by SnallQiu** [comment]
> 你好，我运行到env.test.py的env.reset()时报：TypeError: cannot unpack non-iterable ImageState object错误，我感觉因该是环境数据与返回数据不匹配造成的，但我找了很久都不知道应该修改哪里。能帮我解决下吗？？非常感谢。

Hello, maybe your python keeps a high gym vertion, the biggest change of the high gym vertion is the returned num of the core api `env.step()`, our code based on gym==0.19.0 is OK.

**Comment by zks204** [comment]
非常感谢发自我的手机-------- 原始邮件 --------发件人： SpikeJishuo ***@***.***>日期： 2023年3月6日周一 下午2:17收件人： DRL-Navigation/img_env ***@***.***>抄送： zks204 ***@***.***>, Author ***@***.***>主    题： Re: [DRL-Navigation/img_env] 运行env.test.py时，在env.reset()处报错：TypeError: cannot unpack non-iterable ImageState object (Issue #2)

我也遇到了这个错误，可能因为gym版本太高的不兼容报错，我将gym改为0.22.0版本能够运行了，希望能帮上忙。
